### ISSUE TITLE
`check_exe_basename` broken for python.

### ISSUE THREAD

**Issue by ConnorNelson** [pwncollege/chio#2]
`check_exe_basename` does not work for python.

https://github.com/pwncollege/chio/blob/047fe35671e59f4327d768bded55e6eb42985ae7/chio.py#L75

On production, we get `Executable must be 'python'. Yours is: python3.11`. This also impacts program-interaction.

**Comment by zardus** [comment]
We should:

- change `check_exe_basename` to accept a regular expression instead of just a string (`re.match(basename_regex, os.path.basename(process.exe()))`)
- have check_python and check_ipython do a regex like `r"python(\d(\.\d+)?)?$"`

I don't have the connectivity to test this right now, but if someone wanted to do that, that'd be awesome

**Comment by zardus** [comment]
Looks like @robwaz fixed this, right?

**Comment by robwaz** [comment]
Yes, this can be closed.
